Disable all options

diff --git a/bin/encore b/bin/encore
--- a/bin/encore
+++ b/bin/encore
@@ -16,8 +16,8 @@ fi
 PROJECT_DIR=$(readlink -f "$0" | xargs dirname | xargs dirname)
 cd "${PROJECT_DIR}"
 
-case "${ACTION}" in
-  "production")
+# case "${ACTION}" in
+#   "production")
     mkdir -p "${PROJECT_DIR}/public/build"
     rm -rf "${PROJECT_DIR}/public/build.old"
     docker-compose exec php yarn install
@@ -25,23 +25,23 @@ case "${ACTION}" in
     mv "${PROJECT_DIR}/public/build" "${PROJECT_DIR}/public/build.old"
     mv "${PROJECT_DIR}/public/build.tmp" "${PROJECT_DIR}/public/build"
     cat "${PROJECT_DIR}/public/build/manifest.json" > "${PROJECT_DIR}/var/cache/manifest.json"
-    ;;
-  "dev")
-    # docker-compose exec php yarn run encore dev --verbose
-    cat "${PROJECT_DIR}/public/build/manifest.json" > "${PROJECT_DIR}/var/cache/manifest.json"
-    ;;
-  "dev-server")
-    which inotify-hookable > /dev/null || fail "inotify-hookable is not installed"
-    touch "${PROJECT_DIR}/public/build/manifest.json"
-    inotify-hookable --watch-directories "${PROJECT_DIR}/public/build" --on-modify-path-command "manifest.json=(cp ${PROJECT_DIR}/public/build/manifest.json ${PROJECT_DIR}/var/cache/manifest.json || true)" &
-    #trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT
-    trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
-    # docker-compose exec php yarn serve --host 0.0.0.0 --port 80 --disable-host-check --hot --public=0.0.0.0:80 -d
-    ;;
-  retart)
-    stop
-    start
-    ;;
-  *)
+  # ;;
+  # "dev")
+  #   # docker-compose exec php yarn run encore dev --verbose
+  #   cat "${PROJECT_DIR}/public/build/manifest.json" > "${PROJECT_DIR}/var/cache/manifest.json"
+  #   ;;
+  # "dev-server")
+  #   which inotify-hookable > /dev/null || fail "inotify-hookable is not installed"
+  #   touch "${PROJECT_DIR}/public/build/manifest.json"
+  #   inotify-hookable --watch-directories "${PROJECT_DIR}/public/build" --on-modify-path-command "manifest.json=(cp ${PROJECT_DIR}/public/build/manifest.json ${PROJECT_DIR}/var/cache/manifest.json || true)" &
+  #   #trap 'kill $(jobs -p)' SIGINT SIGTERM EXIT
+  #   trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
+  #   # docker-compose exec php yarn serve --host 0.0.0.0 --port 80 --disable-host-check --hot --public=0.0.0.0:80 -d
+  #   ;;
+  # retart)
+  #   stop
+  #   start
+  #   ;;
+  # *)
     echo "Usage: $0 {production|dev|both|dev-server}"
 esac
